// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(WebApiDbContext))]
    partial class WebApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id")
                        .HasName("PK_Role");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Support"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Email = "test@mail.ru",
                            Name = "Ivan"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Email = "basd@mail.ru",
                            Name = "Petr"
                        },
                        new
                        {
                            Id = 3,
                            Age = 31,
                            Email = "asd@mail.ru",
                            Name = "Konstantin"
                        },
                        new
                        {
                            Id = 4,
                            Age = 21,
                            Email = "fasd@mail.ru",
                            Name = "Alex"
                        },
                        new
                        {
                            Id = 5,
                            Age = 22,
                            Email = "bbsd@mail.ru",
                            Name = "Steve"
                        },
                        new
                        {
                            Id = 6,
                            Age = 22,
                            Email = "basd@mail.ru",
                            Name = "Steve"
                        },
                        new
                        {
                            Id = 7,
                            Age = 22,
                            Email = "basd@mail.ru",
                            Name = "Steve"
                        },
                        new
                        {
                            Id = 8,
                            Age = 23,
                            Email = "qqqd@mail.ru",
                            Name = "Steve"
                        });
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            RoleId = 4,
                            UserId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            UserId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 8
                        });
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("Entities.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
